# Generated by Django 5.2.8 on 2025-12-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0003_alter_jobapplication_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
