# Generated by Django 5.2.8 on 2025-12-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0004_alter_jobapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
