# Generated by Django 5.2.8 on 2025-12-05 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0005_alter_jobapplication_applied_at'),
        ('jobboard', '0003_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobboard.job'),
        ),
    ]
