# Generated by Django 5.2.8 on 2025-12-09 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0006_alter_jobapplication_job'),
        ('jobboard', '0004_remove_job_company_job_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.job'),
        ),
    ]
