# Generated by Django 5.2.8 on 2025-12-09 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0007_alter_jobapplication_job'),
        ('jobboard', '0005_job_applications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobboard.job'),
        ),
    ]
