# Generated by Django 5.2.8 on 2025-12-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0003_alter_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='companies',
            field=models.ManyToManyField(related_name='companies', to='jobboard.company'),
        ),
    ]
